[project]
name = "auto-feedback"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.93.1",
    "pandas>=2.3.1",
    "pyyaml>=6.0.2",
]
